################## Project Specific Entries #######################
#
# These values override other definitions
#
# Project name

PROJECT=roach_bsp
# module ID -> 16 bit hex
BOARD_ID=57005 
REV_MAJOR=0
REV_MINOR=0
# Pin Constraints
PCFILE=constraints/$(PROJECT).ucf
# Enter your source files here space seperated
#      Note: no spaces in filenames
SRC=./modules/toplevel/hdl/toplevel.v \
    ./modules/infrastructure/hdl/infrastructure.v \
    ./modules/reset_block/hdl/reset_block.v \
    ./modules/serial_uart/hdl/serial_uart.v \
    ./modules/as_wb_bridge/hdl/as_wb_bridge.v \
    ./modules/wbm_arbiter/hdl/wbm_arbiter.v \
    ./modules/wbs_arbiter/hdl/wbs_arbiter.v \
    ./modules/wbs_arbiter/hdl/timeout.v \
    ./modules/sys_block/hdl/sys_block.v \
    ./modules/xaui_infrastructure/hdl/xaui_infrastructure.v \
    ./modules/xaui_infrastructure/hdl/transceiver_bank.v \
    ./modules/xaui_infrastructure/hdl/transceiver.v \
    ./modules/xaui_pipe/hdl/xaui_pipe.v \
    ./modules/xaui_pipe/hdl/transfer_engine.v \
    ./modules/xaui_pipe/hdl/xaui_controller.v \
    ./modules/xaui_pipe/hdl/xaui_wb_attach.v \
    ./modules/xaui_pipe/hdl/xaui_fifo.v \
    ./modules/xaui_pipe/hdl/xaui_v7_2.v \
    ./modules/ten_gig_eth/hdl/ten_gb_eth.vhd \
    ./modules/ten_gig_eth/hdl/ten_gig_eth_mac_UCB.vhd \
    ./modules/ten_gig_eth/hdl/wb_attach.v \
    ./modules/ten_gig_eth/hdl/retimer.vhd \
    ./modules/ten_gig_eth/hdl/addr_fifo.v


NETLIST_DIRS=./modules/xaui_pipe/netlist\
             ./modules/ten_gig_eth/netlist

# Module name of toplevel entity
TOPLEVEL_MODULE=toplevel
# Logic Device Part Number
PARTNUM=5vsx50t-ff1136-3

# Verilog Include Directory
VINC=include

GEN_DIR=gen
