################## Project Specific Entries #######################
#
# These values override other definitions
#
# Project name

PROJECT=roach_bsp
# module ID -> 16 bit hex
BOARD_ID=57005 
REV_MAJOR=6
REV_MINOR=1
RCS_UPTODATE=0
REV_RCS=0
# Pin Constraints
PCFILE=constraints/roach_v1-02_bsp.ucf
# Enter your source files here space seperated
#      Note: no spaces in filenames
SRC=./modules/toplevel/hdl/toplevel.v \
    ./modules/infrastructure/hdl/infrastructure.v \
    ./modules/reset_block/hdl/reset_block.v \
    ./modules/epb_infrastructure/hdl/epb_infrastructure.v \
    ./modules/epb_wb_bridge_reg/hdl/epb_wb_bridge_reg.v \
    ./modules/serial_uart/hdl/serial_uart.v \
    ./modules/as_wb_bridge/hdl/as_wb_bridge.v \
    ./modules/wbm_arbiter/hdl/wbm_arbiter.v \
    ./modules/wbs_arbiter/hdl/wbs_arbiter.v \
    ./modules/wbs_arbiter/hdl/timeout.v \
    ./modules/sys_block/hdl/sys_block.v \
    ./modules/sys_block/hdl/v5_sysmon.v \
    ./modules/sys_block/hdl/irq_controller.v \
    ./modules/xaui_infrastructure/hdl/xaui_infrastructure.v \
    ./modules/xaui_infrastructure/hdl/transceiver_bank.v \
    ./modules/xaui_infrastructure/hdl/transceiver.v \
    ./modules/xaui_phy/hdl/xaui_phy.v \
    ./modules/xaui_phy/hdl/xaui_v7_2.v \
    ./modules/xaui_phy/hdl/deskew_state.v \
    ./modules/xaui_phy/hdl/fix_term.v \
    ./modules/xaui_phy/hdl/pcs_deskew.v \
    ./modules/xaui_phy/hdl/pcs_rx.v \
    ./modules/xaui_phy/hdl/pcs_sync.v \
    ./modules/xaui_phy/hdl/pcs_tx.v \
    ./modules/xaui_phy/hdl/sync_state.v \
    ./modules/xaui_phy/hdl/tx_state.v \
    ./modules/xaui_phy/hdl/xaui_kat.v \
    ./modules/ten_gig_eth/hdl/ten_gb_eth.vhd \
    ./modules/ten_gig_eth/hdl/ten_gig_eth_mac_UCB.vhd \
    ./modules/ten_gig_eth/hdl/wb_attach.v \
    ./modules/ten_gig_eth/hdl/retimer.vhd \
    ./modules/ten_gig_eth/hdl/addr_fifo.v \
    ./modules/dram_controller/hdl/dram_controller.v \
    ./modules/dram_controller/hdl/ddr2_ctrl.v \
    ./modules/dram_controller/hdl/ddr2_mem_if_top.v \
    ./modules/dram_controller/hdl/ddr2_phy_calib.v \
    ./modules/dram_controller/hdl/ddr2_phy_ctl_io.v \
    ./modules/dram_controller/hdl/ddr2_phy_dm_iob.v \
    ./modules/dram_controller/hdl/ddr2_phy_dq_iob.v \
    ./modules/dram_controller/hdl/ddr2_phy_dqs_iob.v \
    ./modules/dram_controller/hdl/ddr2_phy_init.v \
    ./modules/dram_controller/hdl/ddr2_phy_io.v \
    ./modules/dram_controller/hdl/ddr2_phy_top.v \
    ./modules/dram_controller/hdl/ddr2_phy_write.v \
    ./modules/dram_controller/hdl/ddr2_usr_addr_fifo.v \
    ./modules/dram_controller/hdl/ddr2_usr_rd.v \
    ./modules/dram_controller/hdl/ddr2_usr_top.v \
    ./modules/dram_controller/hdl/ddr2_usr_wr.v \
    ./modules/dram_cpu_interface/hdl/dram_cpu_interface.v \
    ./modules/dram_cpu_interface/hdl/dram_reg_wb_attach.v \
    ./modules/dram_infrastructure/hdl/dram_infrastructure.v \
    ./modules/multiport_dram/hdl/arbiter.v \
    ./modules/multiport_dram/hdl/fifo_sync.v \
    ./modules/multiport_dram/hdl/multiport_dram.v \
    ./modules/qdr_controller/hdl/qdrc_infrastructure.v \
    ./modules/qdr_controller/hdl/qdrc_phy_burst_align.v \
    ./modules/qdr_controller/hdl/qdrc_phy_bit_train.v \
    ./modules/qdr_controller/hdl/qdrc_phy_bit_correct.v \
    ./modules/qdr_controller/hdl/qdrc_wr.v \
    ./modules/qdr_controller/hdl/qdrc_rd.v \
    ./modules/qdr_controller/hdl/qdrc_phy_bit_align.v \
    ./modules/qdr_controller/hdl/qdrc_phy.v \
    ./modules/qdr_controller/hdl/qdrc_phy_sm.v \
    ./modules/qdr_controller/hdl/qdrc_top.v \
    ./modules/qdr_controller/hdl/qdrii_phy_addr_io.v \
    ./modules/qdr_controller/hdl/qdrii_phy_bw_io.v \
    ./modules/qdr_controller/hdl/qdrii_phy_clk_io.v \
    ./modules/qdr_controller/hdl/qdrii_phy_cq_io.v \
    ./modules/qdr_controller/hdl/qdrii_phy_d_io.v \
    ./modules/qdr_controller/hdl/qdrii_phy_dly_cal_sm.v \
    ./modules/qdr_controller/hdl/qdrii_phy_en.v \
    ./modules/qdr_controller/hdl/qdrii_phy_init_sm.v \
    ./modules/qdr_controller/hdl/qdrii_phy_q_io.v \
    ./modules/qdr_controller/hdl/qdrii_phy_read.v \
    ./modules/qdr_controller/hdl/qdrii_phy_v5_q_io.v \
    ./modules/qdr_controller/hdl/qdrii_phy_write.v \
    ./modules/qdr_controller/hdl/qdrii_top.v \
    ./modules/qdr_controller/hdl/qdrii_top_ctrl_sm.v \
    ./modules/qdr_controller/hdl/qdrii_top_phy.v \
    ./modules/qdr_controller/hdl/qdrii_top_rd_addr_interface.v \
    ./modules/qdr_controller/hdl/qdrii_top_rd_interface.v \
    ./modules/qdr_controller/hdl/qdrii_top_user_interface.v \
    ./modules/qdr_controller/hdl/qdrii_top_wr_addr_interface.v \
    ./modules/qdr_controller/hdl/qdrii_top_wr_data_interface.v \
    ./modules/qdr_controller/hdl/qdrii_top_wr_interface.v \
    ./modules/qdr_controller/hdl/qdrii_top_wrdata_bw_fifo.v \
    ./modules/qdr_controller/hdl/qdrii_top_wrdata_fifo.v \
    ./modules/qdr_controller/hdl/qdr_controller.v \
    ./modules/qdr_infrastructure/hdl/qdr_infrastructure.v \
    ./modules/qdr_cpu_interface/hdl/qdr_cpu_interface.v \
    ./modules/qdr_cpu_interface/hdl/qdr_wb_attach.v \
    ./modules/multiport_qdr/hdl/multiport_qdr.v \
    ./modules/gpio_test/hdl/gpio_test.v \
    ./include/parameters.v \
    ./include/mem_layout.v \
    ./support/roach_app.v


NETLIST_DIRS=./modules/xaui_phy/netlist \
             ./modules/ten_gig_eth/netlist \
             ./modules/iadc_controller/netlist \
             ./modules/roach_app/netlist

# Module name of toplevel entity
TOPLEVEL_MODULE=toplevel
# Logic Device Part Number
PARTNUM=5vsx95t-ff1136-1
#PARTNUM=5vlx110t-ff1136-1

# Verilog Include Directory
VINC=include

GEN_DIR=gen
NETLIST_DIR=netlist
