################## Project Specific Entries #######################
#
# These values override other definitions
#
# Project name

PROJECT=roach_bsp
# module ID -> 16 bit hex
BOARD_ID=57005 
REV_MAJOR=1
REV_MINOR=0
# Pin Constraints
PCFILE=constraints/$(PROJECT).ucf
# Enter your source files here space seperated
#      Note: no spaces in filenames
SRC=./modules/toplevel/hdl/toplevel.v \
    ./modules/infrastructure/hdl/infrastructure.v \
    ./modules/reset_block/hdl/reset_block.v \
    ./modules/epb_infrastructure/hdl/epb_infrastructure.v \
    ./modules/epb_wb_bridge_reg/hdl/epb_wb_bridge_reg.v \
    ./modules/serial_uart/hdl/serial_uart.v \
    ./modules/as_wb_bridge/hdl/as_wb_bridge.v \
    ./modules/wbm_arbiter/hdl/wbm_arbiter.v \
    ./modules/wbs_arbiter/hdl/wbs_arbiter.v \
    ./modules/wbs_arbiter/hdl/timeout.v \
    ./modules/sys_block/hdl/sys_block.v \
    ./modules/xaui_infrastructure/hdl/xaui_infrastructure.v \
    ./modules/xaui_infrastructure/hdl/transceiver_bank.v \
    ./modules/xaui_infrastructure/hdl/transceiver.v \
    ./modules/xaui_pipe/hdl/xaui_pipe.v \
    ./modules/xaui_pipe/hdl/transfer_engine.v \
    ./modules/xaui_pipe/hdl/xaui_controller.v \
    ./modules/xaui_pipe/hdl/xaui_wb_attach.v \
    ./modules/xaui_pipe/hdl/xaui_fifo.v \
    ./modules/xaui_pipe/hdl/xaui_v7_2.v \
    ./modules/ten_gig_eth/hdl/ten_gb_eth.vhd \
    ./modules/ten_gig_eth/hdl/ten_gig_eth_mac_UCB.vhd \
    ./modules/ten_gig_eth/hdl/wb_attach.v \
    ./modules/ten_gig_eth/hdl/retimer.vhd \
    ./modules/ten_gig_eth/hdl/addr_fifo.v \
    ./modules/bram_controller/hdl/bram_controller.v \
    ./modules/ddr2_controller/hdl/ddr2_controller.v \
    ./modules/ddr2_controller/hdl/ctrl.v \
    ./modules/ddr2_controller/hdl/ddr2_sdram.v \
    ./modules/ddr2_controller/hdl/mem_if_top.v \
    ./modules/ddr2_controller/hdl/phy_calib.v \
    ./modules/ddr2_controller/hdl/phy_ctl_io.v \
    ./modules/ddr2_controller/hdl/phy_dm_iob.v \
    ./modules/ddr2_controller/hdl/phy_dq_iob.v \
    ./modules/ddr2_controller/hdl/phy_dqs_iob.v \
    ./modules/ddr2_controller/hdl/phy_init.v \
    ./modules/ddr2_controller/hdl/phy_io.v \
    ./modules/ddr2_controller/hdl/phy_top.v \
    ./modules/ddr2_controller/hdl/phy_write.v \
    ./modules/ddr2_controller/hdl/usr_addr_fifo.v \
    ./modules/ddr2_controller/hdl/usr_rd.v \
    ./modules/ddr2_controller/hdl/usr_top.v \
    ./modules/ddr2_controller/hdl/usr_wr.v \
    ./modules/ddr2_cpu_interface/hdl/ddr2_cpu_interface.v \
    ./modules/ddr2_cpu_interface/hdl/mem_rd_cache.v \
    ./modules/ddr2_cpu_interface/hdl/mem_wr_cache.v \
    ./modules/ddr2_cpu_interface/hdl/reg_wb_attach.v \
    ./modules/ddr2_infrastructure/hdl/ddr2_infrastructure.v \
    ./modules/qdr_controller/hdl/top_ctrl_sm.v \
    ./modules/qdr_controller/hdl/top_wrdata_bw_fifo.v \
    ./modules/qdr_controller/hdl/phy_en.v \
    ./modules/qdr_controller/hdl/phy_dly_cal_sm.v \
    ./modules/qdr_controller/hdl/phy_q_io.v \
    ./modules/qdr_controller/hdl/qdr2_top.v \
    ./modules/qdr_controller/hdl/phy_clk_io.v \
    ./modules/qdr_controller/hdl/top_wrdata_fifo.v \
    ./modules/qdr_controller/hdl/top_phy.v \
    ./modules/qdr_controller/hdl/top_wr_addr_interface.v \
    ./modules/qdr_controller/hdl/phy_bw_io.v \
    ./modules/qdr_controller/hdl/phy_cq_io.v \
    ./modules/qdr_controller/hdl/top_rd_addr_interface.v \
    ./modules/qdr_controller/hdl/phy_addr_io.v \
    ./modules/qdr_controller/hdl/phy_init_sm.v \
    ./modules/qdr_controller/hdl/top_user_interface.v \
    ./modules/qdr_controller/hdl/top_wr_interface.v \
    ./modules/qdr_controller/hdl/top_wr_data_interface.v \
    ./modules/qdr_controller/hdl/phy_read.v \
    ./modules/qdr_controller/hdl/phy_v5_q_io.v \
    ./modules/qdr_controller/hdl/phy_d_io.v \
    ./modules/qdr_controller/hdl/qdr_controller.v \
    ./modules/qdr_controller/hdl/phy_write.v \
    ./modules/qdr_controller/hdl/top_rd_interface.v \
    ./modules/qdr_infrastructure/hdl/qdr_infrastructure.v \
    ./modules/qdr_cpu_interface/hdl/qdr_cpu_interface.v \
    ./modules/qdr_cpu_interface/hdl/reg_wb_attach.v \
    ./modules/iadc_controller/hdl/iadc_controller.v \
    ./modules/iadc_controller/hdl/fifo_72.v \
    ./modules/iadc_infrastructure/hdl/iadc_infrastructure.v


NETLIST_DIRS=./modules/xaui_pipe/netlist\
             ./modules/ten_gig_eth/netlist\
             ./modules/iadc_controller/netlist

# Module name of toplevel entity
TOPLEVEL_MODULE=toplevel
# Logic Device Part Number
PARTNUM=5vlx110t-ff1136-1

# Verilog Include Directory
VINC=include

GEN_DIR=gen
