MODULE_ID=roach_monitor
REV_MAJOR=10
REV_MINOR=1
REV_RCS:=0
RCS_UPTODATE:=0
PROJECT=$(MODULE_ID)_$(REV_MAJOR)_$(REV_MINOR)_$(REV_RCS)

# Directory Defines
SYNTH_DIR=synthesis
PAR_DIR=par
GEN_DIR=gen
CONSTRAINTS_DIR=constraint
INCLUDE_DIR=include
MODULES_DIR=modules
SUPPORT_DIR=support

# File Defines
TOPLEVEL=toplevel
CONSTRAINTS_P=$(CONSTRAINTS_DIR)/$(MODULE_ID).pdc
CONSTRAINTS_T=$(CONSTRAINTS_DIR)/$(MODULE_ID).sdc
SRC=./modules/acm_controller/hdl/acm_controller.v \
    ./modules/adc_controller/hdl/adc_controller.v \
    ./modules/adc_controller/hdl/adc_controller.vh \
    ./modules/analogue_infrastructure/hdl/analogue_infrastructure.v \
    ./modules/as_wb_bridge/hdl/as_wb_bridge.v \
    ./modules/as_wb_bridge/hdl/fifo_512_8.v \
    ./modules/gpio_controller/hdl/gpio_controller.v \
    ./modules/debouncer/hdl/debouncer.v \
    ./modules/dma_engine/hdl/dma_engine.v \
    ./modules/fan_controller/hdl/fan_controller.v \
    ./modules/flashmem_controller/hdl/flashmem_controller.v \
    ./modules/flashmem_controller/hdl/flashmem_controller.vh \
    ./modules/flashmem_infrastructure/hdl/flashmem_infrastructure.v \
    ./modules/from_controller/hdl/from_controller.v \
    ./modules/from_infrastructure/hdl/flashrom_infrastructure.v \
    ./modules/i2c_infrastructure/hdl/i2c_infrastructure.v \
    ./modules/i2c_slave/hdl/i2c_slave.v \
    ./modules/infrastructure/hdl/clock.v \
    ./modules/infrastructure/hdl/infrastructure.v \
    ./modules/infrastructure/hdl/vrpsm.v \
    ./modules/infrastructure/hdl/xtalclk.v \
    ./modules/irq_controller/hdl/irq_controller.v \
    ./modules/irq_controller/hdl/irq_controller.vh \
    ./modules/lc_infrastructure/hdl/lc_infrastructure.v \
    ./modules/level_checker/hdl/level_checker.v \
    ./modules/level_checker/hdl/level_checker.vh \
    ./modules/power_manager/hdl/power_manager.v \
    ./modules/power_manager/hdl/power_manager.vh \
    ./modules/power_manager/hdl/sequencer.v \
    ./modules/reset_block/hdl/reset_block.v \
    ./modules/serial_uart/hdl/log2.v \
    ./modules/serial_uart/hdl/serial_uart.v \
    ./modules/sys_config/hdl/sys_config.v \
    ./modules/sys_config/hdl/sys_config.vh \
    ./modules/toplevel/hdl/toplevel.v \
    ./modules/value_storage/hdl/value_storage.v \
    ./modules/value_storage/hdl/value_storage.vh \
    ./modules/vs_infrastructure/hdl/vs_infrastructure.v \
    ./modules/wbm_arbiter/hdl/wbm_arbiter.v \
    ./modules/wbs_arbiter/hdl/bus_protect.v \
    ./modules/wbs_arbiter/hdl/timeout.v \
    ./modules/wbs_arbiter/hdl/wbs_arbiter.v \
    ./include/parameters.v \
    ./include/memlayout.v

FLASHROM_F = $(PROJECT).ufc
CHEADER_F  = $(PROJECT).h
SYNTH_FILE = $(PROJECT).edn
BIT_FILE   = $(PROJECT).stp
PROG_F     = $(PROJECT).stp
