MODULE_ID=roach_monitor
REV_MAJOR=0
REV_MINOR=1
REV_RCS=0
PROJECT=$(MODULE_ID)_$(REV_MAJOR)

# Directory Defines
SYNTH_DIR=synthesis
PAR_DIR=par
GEN_DIR=gen
CONSTRAINTS_DIR=constraint
INCLUDE_DIR=include
MODULES_DIR=modules
SUPPORT_DIR=support

# File Defines
TOPLEVEL=toplevel
CONSTRAINTS_P=$(CONSTRAINTS_DIR)/$(MODULE_ID).pdc
CONSTRAINTS_T=$(CONSTRAINTS_DIR)/$(MODULE_ID).sdc
SRC=./modules/toplevel/hdl/toplevel.v \
    ./modules/infrastructure/hdl/infrastructure.v \
    ./modules/infrastructure/hdl/clocks.v \
    ./modules/infrastructure/hdl/rcclock.v \
    ./modules/infrastructure/hdl/vrpsm.v \
    ./modules/infrastructure/hdl/xtalclk.v \
    ./modules/reset_block/hdl/reset_block.v \
    ./modules/debouncer/hdl/debouncer.v \
    ./modules/serial_uart/hdl/serial_uart.v \
    ./modules/serial_uart/hdl/log2.v \
    ./modules/as_wb_bridge/hdl/as_wb_bridge.v \
    ./modules/wbm_arbiter/hdl/wbm_arbiter.v \
    ./modules/wbs_arbiter/hdl/wbs_arbiter.v \
    ./modules/wbs_arbiter/hdl/timeout.v \
    ./modules/wbs_arbiter/hdl/bus_protect.v \
    ./modules/sys_config/hdl/sys_config.v \
    ./modules/from_infrastructure/hdl/flashrom_infrastructure.v \
    ./modules/from_controller/hdl/from_controller.v

FLASHROM_F = $(PROJECT).ufc
FLASHMEM_F = $(PROJECT).efc
CHEADER_F  = $(PROJECT).h
SYNTH_FILE = $(PROJECT).edn
BIT_FILE   = $(PROJECT).stp
PROG_F     = $(PROJECT).stp
